Add ionbot reader; read ion mobility from mzid files
compomics/psm_utils pull request #43
Opened 2023-08-21 11:27 UTC by ArthurDeclercq

### Added
- `io`: Add reader for ionbot csv PSM files
- `io.mzid`: Read `ion_mobility`

### Changed
- `io.mzid`: Slightly improved `rt_key` parsing functionality

2023-09-13 15:35 UTC, RalfG requested changes

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +ionbot first csv file parser
**todo:** Add the module to the documentation in `./docs`. Also provide some more info on the type of file (e.g., which version of ionbot was tested?)

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/mzid.py
> +        self._non_metadata_keys.extend([self._im_key, self._spectrum_rt_key])
**todo:** Better not add the keys to `_non_metadata_keys` if they remain `None`.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/mzid.py
> +            # Parse PSM non-metadata keys, rt key, ion  and score key
**nitpick:** Remove double space in comment; perhaps add a `:` after non-metadata keys; did you mean `ion mobility`?
```suggestion
            # Parse PSM non-metadata keys: rt key, ion mobility, and score key
```

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/mzid.py
>                  # Parse PSMs from spectrum
**nitpick:** Can you add the blank line again?

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/mzid.py
> +            raise UnknownMzidScore("No known score metric found in mzIdentML file.")
**question:** Do we want to let the reader crash if no recognized score key is present? Reading PSMs without scores might still be useful in some situations.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/mzid.py
> +        if self._rt_key in sii.keys():
**question:** This is to consider files that might have retention times, but not for all SpectrumIdentificationItems?

2023-09-13 15:35 UTC, RalfG commented on psm_utils/psm.py
> +    def get_mass_shift(self) -> float:
**suggestion:** Perhaps a name like `precursor_mz_error` would be better? Also remove the `get`, as it is a property, not a normal class method.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +
**chore:** Add docstring similar to other readers.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +        return PSMList(psm_list=psm_list)
**todo:** You can replace this by simply calling `self.__iter__` and wrapping the result in a `PSMList`. You can check out the other readers for examples.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +
**nitpick:** Remove the blank line.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +            is_decoy=psm_dict["database"] == "D",
**todo:** Maybe it's better to also check for `T` and else set it to None.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +            # precursor_mz=float(psm_dict["m/z"]),
**todo:** Remove commented line.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +            ),  # what is the ionbot separator?
**question:** Is this resolved?

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +            source="Ionbot",
**nitpick:** "ionbot" is without capital `I`.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +            provenance_data=({"Ionbot_filename": str(self.filename)}),
**nitpick:** "ionbot" is without capital `I`.

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +
**nitpick:** Remove blank line

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +    pass
**question:** Why is this defined here?

2023-09-13 15:35 UTC, RalfG commented on psm_utils/io/ionbot.py
> +class InvalidIonbotModificationError(InvalidPeprecError):
**question:** Why does this inherit from InvalidPeprecError and not from PSMUtilsIOException?

2023-09-15 12:01 UTC, ArthurDeclercq commented on psm_utils/io/mzid.py
> +        if self._rt_key in sii.keys():
No was a leftover from the other implementation with one rt_key for both spectrum and psm level

2023-09-15 13:43 UTC, merged